/*
 *
 * ProfilePage constants
 *
 */

const LOAD_CANDIDATES = 'app/ProfilePage/LOAD_CANDIDATES';
const LOAD_CANDIDATES_SUCCESS = 'app/ProfilePage/LOAD_CANDIDATES_SUCCESS';
const LOAD_CANDIDATES_ERROR = 'app/ProfilePage/LOAD_CANDIDATES_ERROR';

export default {
  LOAD_CANDIDATES,
  LOAD_CANDIDATES_SUCCESS,
  LOAD_CANDIDATES_ERROR,
};
