/*
 *
 * ProfilePage constants
 *
 */

const LOAD_CREW_PREVIEW = '@@tgp/ProfilePage/LOAD_CREW_PREVIEW';
const LOAD_CREW_PREVIEW_SUCCESS = '@@tgp/ProfilePage/LOAD_CREW_PREVIEW_SUCCESS';

const LOAD_USER_SUPPORTED = '@@tgp/ProfilePage/LOAD_USER_SUPPORTED';
const LOAD_USER_SUPPORTED_SUCCESS =
  '@@tgp/ProfilePage/LOAD_USER_SUPPORTED_SUCCESS ';

export default {
  LOAD_CREW_PREVIEW,
  LOAD_CREW_PREVIEW_SUCCESS,

  LOAD_USER_SUPPORTED,
  LOAD_USER_SUPPORTED_SUCCESS,
};
