// const LOAD_INACTIVE_CANDIDATE =
//   '@@tgp/CandidatePage/LOAD_INACTIVE_CANDIDATE';
// const LOAD_CANDIDATE = '@@tgp/CandidatePage/LOAD_CANDIDATE';
// const LOAD_CANDIDATE_SUCCESS = '@@tgp/CandidatePage/LOAD_CANDIDATE_SUCCESS';
// const LOAD_CANDIDATE_ERROR = '@@tgp/CandidatePage/LOAD_CANDIDATE_ERROR';
// const SHARE_IMAGE = '@@tgp/CandidatePage/SHARE_IMAGE';

const SUPPORT = '@@tgp/CandidatePage/SUPPORT';
const SUPPORT_SUCCESS = '@@tgp/CandidatePage/SUPPORT_SUCCESS';
const SUPPORT_ERROR = '@@tgp/CandidatePage/SUPPORT_ERROR';

const CANDIDATE_SUPPORTS = '@@tgp/CandidatePage/CANDIDATE_SUPPORTS';
const CANDIDATE_SUPPORTS_SUCCESS =
  '@@tgp/CandidatePage/CANDIDATE_SUPPORTS_SUCCESS';
const CANDIDATE_SUPPORTS_ERROR = '@@tgp/CandidatePage/CANDIDATE_SUPPORTS_ERROR';

const USER_SUPPORTS = '@@tgp/CandidatePage/USER_SUPPORTS';
const USER_SUPPORTS_SUCCESS = '@@tgp/CandidatePage/USER_SUPPORTS_SUCCESS';
const USER_SUPPORTS_ERROR = '@@tgp/CandidatePage/USER_SUPPORTS_ERROR';

const REMOVE_SUPPORT = '@@tgp/CandidatePage/REMOVE_SUPPORT';

const TRACK_SHARE = '@@tgp/CandidatePage/TRACK_SHARE';

const TRACK_VISIT = '@@tgp/CandidatePage/TRACK_VISIT';

export default {
  SUPPORT,
  SUPPORT_SUCCESS,
  SUPPORT_ERROR,

  CANDIDATE_SUPPORTS,
  CANDIDATE_SUPPORTS_SUCCESS,
  CANDIDATE_SUPPORTS_ERROR,

  USER_SUPPORTS,
  USER_SUPPORTS_SUCCESS,
  USER_SUPPORTS_ERROR,

  REMOVE_SUPPORT,

  TRACK_SHARE,

  TRACK_VISIT,
};
