const LOAD_ARTICLES_FEEDBACK = '@@tgpAdminArticlesPage/LOAD_ARTICLES_FEEDBACK';
const LOAD_ARTICLES_FEEDBACK_SUCCESS =
  '@@tgpAdminArticlesPage/LOAD_ARTICLES_FEEDBACK_SUCCESS';

export default {
  LOAD_ARTICLES_FEEDBACK,
  LOAD_ARTICLES_FEEDBACK_SUCCESS,
};
