/*
 *
 * RegisterPage constants
 *
 */

const REGISTER = '@@tgp/RegisterPage/REGISTER';
const SOCIAL_REGISTER = '@@tgp/RegisterPage/SOCIAL_REGISTER';
const TWITTER_REGISTER = '@@tgp/RegisterPage/TWITTER_REGISTER';
const VERIFY_RECAPTCHA = '@@tgp/RegisterPage/VERIFY_RECAPTCHA';
const VERIFY_RECAPTCHA_SUCCESS = '@@tgp/RegisterPage/VERIFY_RECAPTCHA_SUCCESS';
const VERIFY_RECAPTCHA_ERROR = '@@tgp/RegisterPage/VERIFY_RECAPTCHA_ERROR';

export default {
  REGISTER,
  SOCIAL_REGISTER,
  TWITTER_REGISTER,
  VERIFY_RECAPTCHA,
  VERIFY_RECAPTCHA_SUCCESS,
  VERIFY_RECAPTCHA_ERROR,
};
