/*
 *
 * PortalCampaignManagerPage constants
 *
 */

const FIND_CANDIDATE_POSITIONS = '@@tgp/TopIssuesPage/FIND_CANDIDATE_POSITIONS';
const FIND_CANDIDATE_POSITIONS_SUCCESS =
  '@@tgp/TopIssuesPage/FIND_CANDIDATE_POSITIONS_SUCCESS';

const SAVE_CANDIDATE_POSITION = '@@tgp/TopIssuesPage/SAVE_CANDIDATE_POSITION';
const UPDATE_CANDIDATE_POSITION =
  '@@tgp/TopIssuesPage/UPDATE_CANDIDATE_POSITION';
const DELETE_CANDIDATE_POSITION =
  '@@tgp/TopIssuesPage/DELETE_CANDIDATE_POSITION';

export default {
  FIND_CANDIDATE_POSITIONS,
  FIND_CANDIDATE_POSITIONS_SUCCESS,

  SAVE_CANDIDATE_POSITION,
  UPDATE_CANDIDATE_POSITION,
  DELETE_CANDIDATE_POSITION,
};
