const REGISTER = '@@tgp/user/REGISTER';
const REGISTER_SUCCESS = '@@tgp/user/REGISTER_SUCCESS';
const REGISTER_ERROR = '@@tgp/user/REGISTER_ERROR';

const RESEND_EMAIL = '@@tgp/user/RESEND_EMAIL';

const CONFIRM_EMAIL = '@@tgp/user/CONFIRM_EMAIL';
const CONFIRM_EMAIL_SUCCESS = '@@tgp/user/CONFIRM_EMAIL_SUCCESS';
const CONFIRM_EMAIL_ERROR = '@@tgp/user/CONFIRM_EMAIL_ERROR';

const LOAD_USER_FROM_COOKIE = '@@tgp/user/LOAD_USER_FROM_COOKIE';

const SIGN_OUT = '@@tgp/user/SIGN_OUT';

const LOGIN = '@@tgp/user/LOGIN';

const UPDATE_PRESIDENTIAL_RANK = '@@tgp/user/UPDATE_PRESIDENTIAL_RANK';
const UPDATE_SENATE_RANK = '@@tgp/user/UPDATE_SENATE_RANK';
const UPDATE_HOUSE_RANK = '@@tgp/user/UPDATE_HOUSE_RANK';

const UPDATE_USER = '@@tgp/user/UPDATE_USER';
const UPDATE_USER_SUCCESS = '@@tgp/user/UPDATE_USER_SUCCESS';

export default {
  REGISTER,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
  RESEND_EMAIL,
  CONFIRM_EMAIL,
  CONFIRM_EMAIL_SUCCESS,
  CONFIRM_EMAIL_ERROR,
  LOAD_USER_FROM_COOKIE,
  SIGN_OUT,
  LOGIN,
  UPDATE_PRESIDENTIAL_RANK,
  UPDATE_SENATE_RANK,
  UPDATE_HOUSE_RANK,
  UPDATE_USER,
  UPDATE_USER_SUCCESS,
};
