const LOAD_CANDIDATE = '@@tgp/candidateNewPage/LOAD_CANDIDATE';
const LOAD_CANDIDATE_SUCCESS = '@@tgp/candidateNewPage/LOAD_CANDIDATE_SUCCESS';
const LOAD_CANDIDATE_ERROR = '@@tgp/candidateNewPage/LOAD_CANDIDATE_ERROR';
const SHARE_IMAGE = '@@tgp/candidateNewPage/SHARE_IMAGE';

const SUPPORT = '@@tgp/candidateNewPage/SUPPORT';
const SUPPORT_SUCCESS = '@@tgp/candidateNewPage/SUPPORT_SUCCESS';
const SUPPORT_ERROR = '@@tgp/candidateNewPage/SUPPORT_ERROR';

const CANDIDATE_SUPPORTS = '@@tgp/candidateNewPage/CANDIDATE_SUPPORTS';
const CANDIDATE_SUPPORTS_SUCCESS =
  '@@tgp/candidateNewPage/CANDIDATE_SUPPORTS_SUCCESS';
const CANDIDATE_SUPPORTS_ERROR =
  '@@tgp/candidateNewPage/CANDIDATE_SUPPORTS_ERROR';

const USER_SUPPORTS = '@@tgp/candidateNewPage/USER_SUPPORTS';
const USER_SUPPORTS_SUCCESS = '@@tgp/candidateNewPage/USER_SUPPORTS_SUCCESS';
const USER_SUPPORTS_ERROR = '@@tgp/candidateNewPage/USER_SUPPORTS_ERROR';

const REMOVE_SUPPORT = '@@tgp/candidateNewPage/REMOVE_SUPPORT';
const UPDATE_SUPPORT = '@@tgp/candidateNewPage/UPDATE_SUPPORT';
const ADMIN_DELETE_SUPPORT = '@@tgp/candidateNewPage/ ADMIN_DELETE_SUPPORT';

const TRACK_SHARE = '@@tgp/candidateNewPage/TRACK_SHARE';

export default {
  LOAD_CANDIDATE,
  LOAD_CANDIDATE_SUCCESS,
  LOAD_CANDIDATE_ERROR,
  SHARE_IMAGE,

  SUPPORT,
  SUPPORT_SUCCESS,
  SUPPORT_ERROR,

  CANDIDATE_SUPPORTS,
  CANDIDATE_SUPPORTS_SUCCESS,
  CANDIDATE_SUPPORTS_ERROR,

  USER_SUPPORTS,
  USER_SUPPORTS_SUCCESS,
  USER_SUPPORTS_ERROR,

  REMOVE_SUPPORT,
  UPDATE_SUPPORT,
  ADMIN_DELETE_SUPPORT,

  TRACK_SHARE,
};
