/*
 *
 * AdminPage constants
 *
 */

const LOAD_CANDIDATES = '@@tgpAdminPage/LOAD_CANDIDATES';
const LOAD_CANDIDATES_SUCCESS = '@@tgpAdminPage/LOAD_CANDIDATES_SUCCESS';
const LOAD_CANDIDATES_ERROR = '@@tgpAdminPage/LOAD_CANDIDATES_ERROR';

const LOAD_ALL_USERS = '@@tgpAdminPage/LOAD_ALL_USERS';
const LOAD_ALL_USERS_SUCCESS = '@@tgpAdminPage/LOAD_ALL_USERS_SUCCESS';
const LOAD_ALL_USERS_ERROR = '@@tgpAdminPage/LOAD_ALL_USERS_ERROR';

const UPDATE_CANDIDATE = '@@tgpAdminPage/UPDATE_CANDIDATE';
const UPDATE_CANDIDATE_SUCCESS = '@@tgpAdminPage/UPDATE_CANDIDATE_SUCCESS';

const LOAD_ARTICLES_FEEDBACK = '@@tgpAdminPage/LOAD_ARTICLES_FEEDBACK';
const LOAD_ARTICLES_FEEDBACK_SUCCESS =
  '@@tgpAdminPage/LOAD_ARTICLES_FEEDBACK_SUCCESS';

export default {
  LOAD_CANDIDATES,
  LOAD_CANDIDATES_SUCCESS,
  LOAD_CANDIDATES_ERROR,
  LOAD_ALL_USERS,
  LOAD_ALL_USERS_SUCCESS,
  LOAD_ALL_USERS_ERROR,
  UPDATE_CANDIDATE,
  UPDATE_CANDIDATE_SUCCESS,
  LOAD_ARTICLES_FEEDBACK,
  LOAD_ARTICLES_FEEDBACK_SUCCESS,
};
