/*
 *
 * AdminPage constants
 *
 */

const LOAD_CANDIDATES = '@@tgpAdminPage/LOAD_CANDIDATES';
const LOAD_CANDIDATES_SUCCESS = '@@tgpAdminPage/LOAD_CANDIDATES_SUCCESS';
const LOAD_CANDIDATES_ERROR = '@@tgpAdminPage/LOAD_CANDIDATES_ERROR';

const UPDATE_CANDIDATE = '@@tgpAdminPage/UPDATE_CANDIDATE';
const UPDATE_CANDIDATE_SUCCESS = '@@tgpAdminPage/UPDATE_CANDIDATE_SUCCESS';

export default {
  LOAD_CANDIDATES,
  LOAD_CANDIDATES_SUCCESS,
  LOAD_CANDIDATES_ERROR,

  UPDATE_CANDIDATE,
  UPDATE_CANDIDATE_SUCCESS,
};
