const LOAD_ALL_USERS = '@@tgpAdminUsersPage/LOAD_ALL_USERS';
const LOAD_ALL_USERS_SUCCESS = '@@tgpAdminUsersPage/LOAD_ALL_USERS_SUCCESS';
const LOAD_ALL_USERS_ERROR = '@@tgpAdminUsersPage/LOAD_ALL_USERS_ERROR';

const DELETE_USER = '@@tgpAdminUsersPage/DELETE_USER';

const UPDATE_CANDIDATE = '@@tgpAdminUsersPage/UPDATE_CANDIDATE';

export default {
  LOAD_ALL_USERS,
  LOAD_ALL_USERS_SUCCESS,
  LOAD_ALL_USERS_ERROR,
  DELETE_USER,
  UPDATE_CANDIDATE,
};
