const LOAD_ALL_CANDIDATES = '@@tgp/scrape/LOAD_ALL_CANDIDATES';
const LOAD_ALL_CANDIDATES_SUCCESS = '@@tgp/scrape/LOAD_ALL_CANDIDATES_SUCCESS';
const LOAD_ALL_CANDIDATES_ERROR = '@@tgp/scrape/LOAD_ALL_CANDIDATES_ERROR';

export default {
  LOAD_ALL_CANDIDATES,
  LOAD_ALL_CANDIDATES_SUCCESS,
  LOAD_ALL_CANDIDATES_ERROR,
};
