/*
 *
 * HomePage constants
 *
 */

const LOAD_CHALLENGERS = '@@tgpHomePage/LOAD_CHALLENGERS';
const LOAD_CHALLENGERS_SUCCESS = '@@tgpHomePage/LOAD_CHALLENGERS_SUCCESS';
const LOAD_CHALLENGERS_ERROR = '@@tgpHomePage/LOAD_CHALLENGERS_ERROR';
const SUBSCRIBE_EMAIL = '@@tgpHomePage/SUBSCRIBE_EMAIL';

export default {
	LOAD_CHALLENGERS,
	LOAD_CHALLENGERS_ERROR,
	LOAD_CHALLENGERS_SUCCESS,
	SUBSCRIBE_EMAIL
}