/*
 *
 * HomePage constants
 *
 */

const LOAD_HOMEPAGE_CANDIDATES = '@@tgpHomePage/LOAD_HOMEPAGE_CANDIDATES';
const LOAD_HOMEPAGE_CANDIDATES_SUCCESS =
  '@@tgpHomePage/LOAD_HOMEPAGE_CANDIDATES_SUCCESS';
const LOAD_HOMEPAGE_CANDIDATES_ERROR =
  '@@tgpHomePage/LOAD_HOMEPAGE_CANDIDATES_ERROR';
const SUBSCRIBE_EMAIL = '@@tgpHomePage/SUBSCRIBE_EMAIL';

const LOAD_FEED = '@@tgpHomePage/LOAD_FEED';
const LOAD_FEED_SUCCESS = '@@tgpHomePage/LOAD_FEED_SUCCESS';

export default {
  LOAD_HOMEPAGE_CANDIDATES,
  LOAD_HOMEPAGE_CANDIDATES_ERROR,
  LOAD_HOMEPAGE_CANDIDATES_SUCCESS,
  SUBSCRIBE_EMAIL,

  LOAD_FEED,
  LOAD_FEED_SUCCESS
};
