const LOAD_CONTENT = '@@tgp/global/LOAD_CONTENT';
const LOAD_CONTENT_SUCCESS = '@@tgp/global/LOAD_CONTENT_SUCCESS';
const LOAD_CONTENT_ERROR = '@@tgp/global/LOAD_CONTENT_ERROR';

const SET_ARTICLE_MODAL = '@@tgp/global/SET_ARTICLE_MODAL';
const CLEAR_ARTICLE_MODAL = '@@tgp/global/CLEAR_ARTICLE_MODAL';

const SEND_ARTICLE_FEEDBACK = '@@tgp/global/SEND_ARTICLE_FEEDBACK';

const LOG_ERROR = '@@tgp/global/LOG_ERROR';
const REFRESH_TOKEN = '@@tgp/user/REFRESH_TOKEN';

export default {
  LOAD_CONTENT,
  LOAD_CONTENT_SUCCESS,
  LOAD_CONTENT_ERROR,
  SET_ARTICLE_MODAL,
  CLEAR_ARTICLE_MODAL,
  SEND_ARTICLE_FEEDBACK,
  LOG_ERROR,
  REFRESH_TOKEN,
};
