const LOAD_INCUMBENTS = '@@tgp/incumbentsPage/LOAD_INCUMBENTS';
const LOAD_INCUMBENTS_SUCCESS = '@@tgp/incumbentsPage/LOAD_INCUMBENTS_SUCCESS';
const LOAD_INCUMBENTS_ERROR = '@@tgp/incumbentsPage/LOAD_INCUMBENTS_ERROR';

export default {
  LOAD_INCUMBENTS,
  LOAD_INCUMBENTS_SUCCESS,
  LOAD_INCUMBENTS_ERROR,
};
