const LOAD_CANDIDATE = '@@tgp/candidate/LOAD_CANDIDATE';
const LOAD_CANDIDATE_SUCCESS = '@@tgp/candidate/LOAD_CANDIDATE_SUCCESS';
const LOAD_CANDIDATE_ERROR = '@@tgp/candidate/LOAD_CANDIDATE_ERROR';

const SAVE_RANK_PRESIDENTIAL_CANDIDATE =
  '@@tgp/candidate/SAVE_RANK_PRESIDENTIAL_CANDIDATE';
const SAVE_RANK_SENATE_CANDIDATE = '@@tgp/candidate/SAVE_RANK_SENATE_CANDIDATE';
const SAVE_RANK_HOUSE_CANDIDATE = '@@tgp/candidate/SAVE_RANK_HOUSE_CANDIDATE';

const LOAD_RANKING_FROM_COOKIE = '@@tgp/candidate/LOAD_RANKING_FROM_COOKIE';

const LOAD_DISTRICT_INCUMBENT = '@@tgp/candidate/LOAD_DISTRICT_INCUMBENT';
const LOAD_DISTRICT_INCUMBENT_SUCCESS =
  '@@tgp/candidate/LOAD_DISTRICT_INCUMBENT_SUCCESS';

const LOAD_CANDIDATE_RANKING = '@@tgp/candidate/LOAD_CANDIDATE_RANKING';
const LOAD_CANDIDATE_RANKING_SUCCESS =
  '@@tgp/candidate/LOAD_CANDIDATE_RANKING_SUCCESS';
const LOAD_CANDIDATE_RANKING_ERROR =
  '@@tgp/candidate/LOAD_CANDIDATE_RANKING_ERROR';

export default {
  LOAD_CANDIDATE,
  LOAD_CANDIDATE_SUCCESS,
  LOAD_CANDIDATE_ERROR,
  SAVE_RANK_PRESIDENTIAL_CANDIDATE,
  SAVE_RANK_SENATE_CANDIDATE,
  SAVE_RANK_HOUSE_CANDIDATE,
  LOAD_RANKING_FROM_COOKIE,
  LOAD_DISTRICT_INCUMBENT,
  LOAD_DISTRICT_INCUMBENT_SUCCESS,

  LOAD_CANDIDATE_RANKING,
  LOAD_CANDIDATE_RANKING_SUCCESS,
  LOAD_CANDIDATE_RANKING_ERROR,
};
