const LOAD_CANDIDATE = '@@tgp/candidate/LOAD_CANDIDATE';
const LOAD_CANDIDATE_SUCCESS = '@@tgp/candidate/LOAD_CANDIDATE_SUCCESS';
const LOAD_CANDIDATE_ERROR = '@@tgp/candidate/LOAD_CANDIDATE_ERROR';
const SAVE_RANK_PRESIDENTIAL_CANDIDATE =
  '@@tgp/candidate/SAVE_RANK_PRESIDENTIAL_CANDIDATE';
const SAVE_RANK_SENATE_CANDIDATE = '@@tgp/candidate/SAVE_RANK_SENATE_CANDIDATE';
const SAVE_RANK_HOUSE_CANDIDATE = '@@tgp/candidate/SAVE_RANK_HOUSE_CANDIDATE';

const LOAD_RANKING_FROM_COOKIE = '@@tgp/candidate/LOAD_RANKING_FROM_COOKIE';

export default {
  LOAD_CANDIDATE,
  LOAD_CANDIDATE_SUCCESS,
  LOAD_CANDIDATE_ERROR,
  SAVE_RANK_PRESIDENTIAL_CANDIDATE,
  SAVE_RANK_SENATE_CANDIDATE,
  SAVE_RANK_HOUSE_CANDIDATE,
  LOAD_RANKING_FROM_COOKIE,
};
