const ALL_CANDIDATES = '@@tgp/directory/ALL_CANDIDATES';
const ALL_CANDIDATES_SUCCESS = '@@tgp/directory/ALL_CANDIDATES_SUCCESS';
const ALL_CANDIDATES_ERROR = '@@tgp/directory/ALL_CANDIDATES_ERROR';
export default {
  ALL_CANDIDATES,
  ALL_CANDIDATES_SUCCESS,
  ALL_CANDIDATES_ERROR,
};
