const LOAD_PRESIDENTIAL_CANDIDATE =
  '@@tgp/candidate/LOAD_PRESIDENTIAL_CANDIDATE';
const LOAD_PRESIDENTIAL_CANDIDATE_SUCCESS =
  '@@tgp/candidate/LOAD_PRESIDENTIAL_CANDIDATE_SUCCESS';
const LOAD_PRESIDENTIAL_CANDIDATE_ERROR =
  '@@tgp/candidate/LOAD_PRESIDENTIAL_CANDIDATE_ERROR';
const SAVE_RANK_PRESIDENTIAL_CANDIDATE =
  '@@tgp/candidate/SAVE_RANK_PRESIDENTIAL_CANDIDATE';
const LOAD_RANKING_FROM_COOKIE = '@@tgp/candidate/LOAD_RANKING_FROM_COOKIE';

export default {
  LOAD_PRESIDENTIAL_CANDIDATE,
  LOAD_PRESIDENTIAL_CANDIDATE_SUCCESS,
  LOAD_PRESIDENTIAL_CANDIDATE_ERROR,
  SAVE_RANK_PRESIDENTIAL_CANDIDATE,
  LOAD_RANKING_FROM_COOKIE,
};
