name: Cypress Tests

on: pull_request

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v4
#         with:
#           # build: npm run build
#           start: npm start
#           # cypress: npm run cypress:run:dev

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          # Disable running of tests within install job
          runTests: false

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
    fail-fast: false
    matrix:
      # run copies of the current job in parallel
      containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Run Dev Server'
        run: yarn run dev-dev-pm2

      - name: 'UI Tests - Chrome'
        run: yarn run dev-test
