name: Cypress Tests

on: pull_request
jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - name: 'Run Dev Server'
        run: yarn run dev-dev-pm2

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v4
        with:
          install: false
          record: true
          browser: chrome
          parallel: true
          group: 'UI - Chrome'
        env:
          CYPRESS_RECORD_KEY: 'fad4fb6b-1318-4ba0-883b-8606925d150d'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_BASE_URL: http://localhost:4000
          CYPRESS_API_BASE: https://api-dev.goodparty.org/api/v1/
