name: Cypress Tests

on: pull_request

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v4
#         with:
#           # build: npm run build
#           start: npm start
#           # cypress: npm run cypress:run:dev

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Cypress Install'
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          runTests: false
          browser: chrome
      - name: 'Run Dev Server'
        run: yarn run dev-dev-pm2

      - name: 'UI Tests - Chrome'
        run: yarn run dev-test
