const LOAD_ZIP = '@@tgp/district/LOAD_ZIP';
const LOAD_ZIP_SUCCESS = '@@tgp/district/LOAD_ZIP_SUCCESS';
const LOAD_ZIP_ERROR = '@@tgp/district/LOAD_ZIP_ERROR';

const LOAD_COOKIE_ZIP = '@@tgp/district/LOAD_COOKIE_ZIP';

const LOAD_ALL_PRESIDENTIAL = '@@tgp/district/LOAD_ALL_PRESIDENTIAL';
const LOAD_ALL_PRESIDENTIAL_SUCCESS =
  '@@tgp/district/LOAD_ALL_PRESIDENTIAL_SUCCESS';
const LOAD_ALL_PRESIDENTIAL_ERROR =
  '@@tgp/district/LOAD_ALL_PRESIDENTIAL_ERROR';

const LOAD_DISTRICT_INCUMBENTS = '@@tgp/district/LOAD_DISTRICT_INCUMBENTS';
const LOAD_DISTRICT_INCUMBENTS_SUCCESS =
  '@@tgp/district/LOAD_DISTRICT_INCUMBENTS_SUCCESS';
const LOAD_DISTRICT_INCUMBENTS_ERROR =
  '@@tgp/district/LOAD_DISTRICT_INCUMBENTS_ERROR';

const LOAD_DISTRICT_CANDIDATES = '@@tgp/district/LOAD_DISTRICT_CANDIDATES';
const LOAD_DISTRICT_CANDIDATES_SUCCESS =
  '@@tgp/district/LOAD_DISTRICT_CANDIDATES_SUCCESS';
const LOAD_DISTRICT_CANDIDATES_ERROR =
  '@@tgp/district/LOAD_DISTRICT_CANDIDATES_ERROR';

const GEOLOCATION_TO_DISTRICT = '@@tgp/district/GEOLOCATION_TO_DISTRICT';
const GEOLOCATION_TO_DISTRICT_SUCCESS =
  '@@tgp/district/GEOLOCATION_TO_DISTRICT_SUCCESS';
const GEOLOCATION_TO_DISTRICT_ERROR =
  '@@tgp/district/GEOLOCATION_TO_DISTRICT_ERROR';

export default {
  LOAD_ZIP,
  LOAD_ZIP_SUCCESS,
  LOAD_ZIP_ERROR,
  LOAD_COOKIE_ZIP,
  LOAD_ALL_PRESIDENTIAL,
  LOAD_ALL_PRESIDENTIAL_SUCCESS,
  LOAD_ALL_PRESIDENTIAL_ERROR,
  LOAD_DISTRICT_INCUMBENTS,
  LOAD_DISTRICT_INCUMBENTS_SUCCESS,
  LOAD_DISTRICT_INCUMBENTS_ERROR,
  LOAD_DISTRICT_CANDIDATES,
  LOAD_DISTRICT_CANDIDATES_SUCCESS,
  LOAD_DISTRICT_CANDIDATES_ERROR,
  GEOLOCATION_TO_DISTRICT,
  GEOLOCATION_TO_DISTRICT_SUCCESS,
  GEOLOCATION_TO_DISTRICT_ERROR,
};
