const LOAD_ZIP = '@@tgp/district/LOAD_ZIP';
const LOAD_ZIP_SUCCESS = '@@tgp/district/LOAD_ZIP_SUCCESS';
const LOAD_ZIP_ERROR = '@@tgp/district/LOAD_ZIP_ERROR';

const LOAD_COOKIE_ZIP = '@@tgp/district/LOAD_COOKIE_ZIP';

const LOAD_ALL_PRESIDENTIAL = '@@tgp/district/LOAD_ALL_PRESIDENTIAL';
const LOAD_ALL_PRESIDENTIAL_SUCCESS =
  '@@tgp/district/LOAD_ALL_PRESIDENTIAL_SUCCESS';
const LOAD_ALL_PRESIDENTIAL_ERROR =
  '@@tgp/district/LOAD_ALL_PRESIDENTIAL_ERROR';

const LOAD_HOUSE_CANDIDATES = '@@tgp/district/LOAD_HOUSE_CANDIDATES';
const LOAD_HOUSE_CANDIDATES_SUCCESS =
  '@@tgp/district/LOAD_HOUSE_CANDIDATES_SUCCESS';
const LOAD_HOUSE_CANDIDATES_ERROR =
  '@@tgp/district/LOAD_HOUSE_CANDIDATES_ERROR';

const LOAD_SENATE_CANDIDATES = '@@tgp/district/LOAD_SENATE_CANDIDATES';
const LOAD_SENATE_CANDIDATES_SUCCESS =
  '@@tgp/district/LOAD_SENATE_CANDIDATES_SUCCESS';
const LOAD_SENATE_CANDIDATES_ERROR =
  '@@tgp/district/LOAD_SENATE_CANDIDATES_ERROR';

const GEOLOCATION_TO_DISTRICT = '@@tgp/district/GEOLOCATION_TO_DISTRICT';
const GEOLOCATION_TO_DISTRICT_SUCCESS =
  '@@tgp/district/GEOLOCATION_TO_DISTRICT_SUCCESS';
const GEOLOCATION_TO_DISTRICT_ERROR =
  '@@tgp/district/GEOLOCATION_TO_DISTRICT_ERROR';

const USERS_COUNTS = '@@tgp/district/USERS_COUNTS';
const USERS_COUNTS_SUCCESS = '@@tgp/district/USERS_COUNTS_SUCCESS';

const LOAD_BLOC_CANDIDATE = '@@tgp/district/LOAD_BLOC_CANDIDATE';
const LOAD_BLOC_CANDIDATE_SUCCESS =
  '@@tgp/district/LOAD_BLOC_CANDIDATE_SUCCESS';
const CLEAR_BLOC_CANDIDATE = '@@tgp/district/CLEAR_BLOC_CANDIDATE';

const SET_JOIN_CANDIDATE = '@@tgp/district/SET_JOIN_CANDIDATE';
const CLEAR_JOIN_CANDIDATE = '@@tgp/district/CLEAR_JOIN_CANDIDATE';

export default {
  LOAD_ZIP,
  LOAD_ZIP_SUCCESS,
  LOAD_ZIP_ERROR,
  LOAD_COOKIE_ZIP,
  LOAD_ALL_PRESIDENTIAL,
  LOAD_ALL_PRESIDENTIAL_SUCCESS,
  LOAD_ALL_PRESIDENTIAL_ERROR,
  LOAD_HOUSE_CANDIDATES,
  LOAD_HOUSE_CANDIDATES_SUCCESS,
  LOAD_HOUSE_CANDIDATES_ERROR,
  LOAD_SENATE_CANDIDATES,
  LOAD_SENATE_CANDIDATES_SUCCESS,
  LOAD_SENATE_CANDIDATES_ERROR,
  GEOLOCATION_TO_DISTRICT,
  GEOLOCATION_TO_DISTRICT_SUCCESS,
  GEOLOCATION_TO_DISTRICT_ERROR,
  USERS_COUNTS,
  USERS_COUNTS_SUCCESS,
  LOAD_BLOC_CANDIDATE,
  LOAD_BLOC_CANDIDATE_SUCCESS,
  CLEAR_BLOC_CANDIDATE,
  SET_JOIN_CANDIDATE,
  CLEAR_JOIN_CANDIDATE,
};
